FROM ghcr.io/insight-platform/manylinux_2_28_x64:v0.0.7 as builder

WORKDIR /opt
COPY . .
ARG PYTHON_INTERPRETER
RUN chmod +x /opt/docker/build-manylinux.sh
RUN bash /opt/docker/build-manylinux.sh
RUN rm -rf target

FROM alpine:3.18 as dist
COPY --from=builder /opt/dist /opt/dist
