FROM ghcr.io/insight-platform/manylinux_2_28_arm64:v0.0.3 as builder

WORKDIR /opt
COPY . .
ARG PYTHON_INTERPRETER
RUN bash /opt/docker/build-manylinux.sh
RUN rm -rf target

FROM alpine:3.18 as dist
COPY --from=builder /opt/dist /opt/dist
