# Default tracker and evaluator configuration.
# Use as a template to configure

# unique run name (used to build resulting folder)
name: maha_sort

# data location configuration, mot challenge format
# detection and ground truth files location
# ground truth file: {data_path}/{sample}/gt/gt.txt
# detection file: {data_path}/{sample}/det/det.txt
data_path: /data/MOT20/train
# tracker and evaluation output path
# tracker predicted detections file: {output_path}/{name}/{sample}.txt
# tracker evaluation output folder: {output_path}/{name}/data
output_path: /data/MOT20/output

# tracker configuration
tracker:
  # supported tracker types:
  #  type: Sort
  #  type: VisualSort [TODO]
  #  type: OriginalSort (https://github.com/abewley/sort)
  type: Sort
  # tracker initialization parameters
  params:
    # amount of cpu threads to process the data, default 4
    shards: 4
    # how many last bboxes are kept within stored track, default 10
    bbox_history: 10
    # how long track survives without being updated, default 10
    max_idle_epochs: 100
    # tracker positional metric configuration, default IoU
    positional_metric:
      # supported types: IoU, Maha (Mahalanobis)
      type: Maha
    # constraints for objects compared across different epochs (epoch_delta, max_allowed_distance)
    spatio_temporal_constraints:
      - [1, 1.0]
    # whether to use bounding box confidences
    use_confidence: false

# evaluator configuration
evaluator:
  # number of cores to use
  num_cores: 4
